services:
  redis:
    image: redis:7.4-alpine
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5
    command:
      - redis-server
      - --dir /data
      - --dbfilename dump.rdb
      - --save 60 100
      - --save 300 1
      - --appendonly yes
      - --appendfsync everysec
      - --auto-aof-rewrite-percentage 100
      - --auto-aof-rewrite-min-size 64mb

volumes:
  redis-data:
